# Generated by Django 5.0 on 2025-12-29 23:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('equipment', 'Sprzęt'), ('materials', 'Materiały'), ('labor', 'Robocizna'), ('fuel', 'Paliwo'), ('tools', 'Narzędzia'), ('electrical', 'Elektryka'), ('plumbing', 'Hydraulika'), ('other', 'Inne')], max_length=50, unique=True, verbose_name='Nazwa kategorii')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
            ],
            options={
                'verbose_name': 'Kategoria zakupu',
                'verbose_name_plural': 'Kategorie zakupów',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('salon', 'Salon'), ('sypialnia', 'Sypialnia'), ('kuchnia', 'Kuchnia'), ('lazienka', 'Łazienka'), ('ubikacja', 'Ubikacja'), ('pokoj_dzieciecy', 'Pokój Dziecięcy'), ('biuro', 'Biuro'), ('korytarz', 'Korytarz'), ('loggia', 'Loggia')], max_length=50, unique=True, verbose_name='Nazwa pomieszczenia')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('square_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Powierzchnia (m²)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
            ],
            options={
                'verbose_name': 'Pomieszczenie',
                'verbose_name_plural': 'Pomieszczenia',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('description', models.TextField(verbose_name='Opis postępu')),
                ('notes', models.TextField(blank=True, verbose_name='Dodatkowe notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='renovation.room', verbose_name='Pomieszczenie')),
            ],
            options={
                'verbose_name': 'Postęp prac',
                'verbose_name_plural': 'Postępy prac',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomProgressPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='progress/%Y/%m/', verbose_name='Zdjęcie')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Podpis')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data przesłania')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='renovation.roomprogress', verbose_name='Postęp')),
            ],
            options={
                'verbose_name': 'Zdjęcie postępu',
                'verbose_name_plural': 'Zdjęcia postępu',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('start_time', models.TimeField(verbose_name='Godzina rozpoczęcia')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Godzina zakończenia')),
                ('notes', models.TextField(verbose_name='Notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('rooms_worked_on', models.ManyToManyField(blank=True, related_name='work_sessions', to='renovation.room', verbose_name='Pomieszczenia')),
            ],
            options={
                'verbose_name': 'Sesja pracy',
                'verbose_name_plural': 'Sesje pracy',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data zakupu')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Kwota')),
                ('vendor', models.CharField(max_length=200, verbose_name='Sklep/Dostawca')),
                ('description', models.TextField(verbose_name='Opis')),
                ('receipt_photo', models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/', verbose_name='Zdjęcie paragonu')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='renovation.purchasecategory', verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Zakup',
                'verbose_name_plural': 'Zakupy',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['-date'], name='renovation__date_abeb35_idx'), models.Index(fields=['category', '-date'], name='renovation__categor_0c4dc4_idx')],
            },
        ),
        migrations.CreateModel(
            name='ElectricalCircuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit_name', models.CharField(max_length=100, verbose_name='Nazwa obwodu')),
                ('breaker_number', models.CharField(max_length=20, verbose_name='Numer bezpiecznika/wyłącznika')),
                ('connected_appliances', models.TextField(help_text='Lista urządzeń podłączonych do tego obwodu', verbose_name='Podłączone urządzenia')),
                ('amperage', models.PositiveIntegerField(blank=True, help_text='Natężenie prądu w amperach', null=True, verbose_name='Amperaż (A)')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='circuits', to='renovation.room', verbose_name='Pomieszczenie')),
            ],
            options={
                'verbose_name': 'Obwód elektryczny',
                'verbose_name_plural': 'Obwody elektryczne',
                'ordering': ['breaker_number', 'circuit_name'],
                'indexes': [models.Index(fields=['room'], name='renovation__room_id_fcc41c_idx'), models.Index(fields=['breaker_number'], name='renovation__breaker_2b5790_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='roomprogress',
            index=models.Index(fields=['room', '-date'], name='renovation__room_id_f79147_idx'),
        ),
        migrations.AddIndex(
            model_name='roomprogress',
            index=models.Index(fields=['-date'], name='renovation__date_47f2f7_idx'),
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['-date', '-start_time'], name='renovation__date_262faf_idx'),
        ),
    ]
