# Generated by Django 5.2.9 on 2025-12-30 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renovation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['property', 'name'], 'verbose_name': 'Pomieszczenie', 'verbose_name_plural': 'Pomieszczenia'},
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(choices=[('salon', 'Salon'), ('sypialnia', 'Sypialnia'), ('kuchnia', 'Kuchnia'), ('lazienka', 'Łazienka'), ('ubikacja', 'Ubikacja'), ('pokoj_dzieciecy', 'Pokój Dziecięcy'), ('biuro', 'Biuro'), ('korytarz', 'Korytarz'), ('loggia', 'Loggia')], max_length=50, verbose_name='Nazwa pomieszczenia'),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('street_address', models.CharField(max_length=200, verbose_name='Ulica i numer')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Kod pocztowy')),
                ('city', models.CharField(max_length=100, verbose_name='Miasto')),
                ('country', models.CharField(default='Poland', max_length=100, verbose_name='Kraj')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('renovation_start_date', models.DateField(blank=True, null=True, verbose_name='Data rozpoczęcia remontu')),
                ('renovation_end_date', models.DateField(blank=True, null=True, verbose_name='Data zakończenia remontu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='Właściciel')),
            ],
            options={
                'verbose_name': 'Nieruchomość',
                'verbose_name_plural': 'Nieruchomości',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='renovation.property', verbose_name='Nieruchomość'),
        ),
        migrations.AddField(
            model_name='room',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='renovation.property', verbose_name='Nieruchomość'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('property', 'name')},
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['owner', 'is_active'], name='renovation__owner_i_30cdef_idx'),
        ),
    ]
