# Generated by Django 5.2.9 on 2025-12-30 11:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renovation', '0002_alter_room_options_alter_room_name_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_status',
            field=models.TextField(blank=True, verbose_name='Aktualny status'),
        ),
        migrations.AddField(
            model_name='room',
            name='floor_type',
            field=models.CharField(blank=True, choices=[('plytki', 'Płytki'), ('panele', 'Panele'), ('parkiet', 'Parkiet'), ('wykladzina_dywanowa', 'Wykładzina dywanowa')], max_length=50, verbose_name='Typ podłogi'),
        ),
        migrations.AddField(
            model_name='room',
            name='future_plans',
            field=models.TextField(blank=True, verbose_name='Plany na przyszłość'),
        ),
        migrations.AddField(
            model_name='room',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Wysokość (m)'),
        ),
        migrations.AddField(
            model_name='room',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Długość (m)'),
        ),
        migrations.AddField(
            model_name='room',
            name='progress_notes',
            field=models.TextField(blank=True, verbose_name='Notatki o postępie'),
        ),
        migrations.AddField(
            model_name='room',
            name='progress_percentage',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Postęp (%)'),
        ),
        migrations.AddField(
            model_name='room',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Krótka nazwa'),
        ),
        migrations.AddField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
        migrations.AddField(
            model_name='room',
            name='wall_finishes',
            field=models.CharField(blank=True, help_text='Oddziel przecinkami, np: farba,tapeta', max_length=200, verbose_name='Wykończenie ścian'),
        ),
        migrations.AddField(
            model_name='room',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Szerokość (m)'),
        ),
    ]
