# Generated by Django 5.2.9 on 2025-12-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renovation', '0003_room_current_status_room_floor_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='custom_name',
            field=models.CharField(blank=True, help_text='Wypełnij gdy wybrano "Inne - Własna nazwa"', max_length=100, verbose_name='Własna nazwa pomieszczenia'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(choices=[('salon', 'Salon'), ('sypialnia', 'Sypialnia'), ('kuchnia', 'Kuchnia'), ('lazienka', 'Łazienka'), ('ubikacja', 'Ubikacja'), ('pokoj_dzieciecy', 'Pokój Dziecięcy'), ('biuro', 'Biuro'), ('korytarz', 'Korytarz'), ('loggia', 'Loggia'), ('other', 'Inne - Własna nazwa')], max_length=50, verbose_name='Nazwa pomieszczenia'),
        ),
    ]
