# Generated by Django 5.2.9 on 2025-12-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renovation', '0004_room_custom_name_alter_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='custom_name',
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(choices=[('salon', 'Salon'), ('sypialnia', 'Sypialnia'), ('kuchnia', 'Kuchnia'), ('lazienka', 'Łazienka'), ('ubikacja', 'Ubikacja'), ('pokoj_dzieciecy', 'Pokój Dziecięcy'), ('biuro', 'Biuro'), ('korytarz', 'Korytarz'), ('loggia', 'Loggia')], max_length=50, verbose_name='Typ pomieszczenia'),
        ),
        migrations.CreateModel(
            name='DropdownChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_type', models.CharField(choices=[('room_type', 'Typ pomieszczenia'), ('floor_type', 'Typ podłogi'), ('wall_finish', 'Wykończenie ścian'), ('purchase_category', 'Kategoria zakupu')], max_length=50, verbose_name='Typ pola')),
                ('value', models.CharField(max_length=100, verbose_name='Wartość (klucz)')),
                ('label_pl', models.CharField(max_length=200, verbose_name='Etykieta (PL)')),
                ('label_en', models.CharField(max_length=200, verbose_name='Etykieta (EN)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Kolejność wyświetlania')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
            ],
            options={
                'verbose_name': 'Opcja rozwijanej listy',
                'verbose_name_plural': 'Opcje rozwijanej listy',
                'ordering': ['choice_type', 'display_order', 'label_pl'],
                'indexes': [models.Index(fields=['choice_type', 'is_active'], name='renovation__choice__910c5e_idx')],
                'unique_together': {('choice_type', 'value')},
            },
        ),
    ]
