# Generated by Django 5.2.9 on 2025-12-30 11:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renovation', '0005_remove_room_custom_name_alter_room_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa narzędzia/sprzętu')),
                ('purpose', models.TextField(help_text='Do czego głównie służy to narzędzie/sprzęt', verbose_name='Przeznaczenie')),
                ('condition', models.CharField(choices=[('ok', 'OK - Sprawny'), ('broken', 'Zepsuty'), ('missing_parts', 'Brakuje części')], default='ok', max_length=20, verbose_name='Stan techniczny')),
                ('is_old', models.BooleanField(default=False, help_text='Zaznacz jeśli nie posiadasz danych o zakupie', verbose_name='Stary sprzęt')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Data zakupu')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cena zakupu')),
                ('vendor', models.CharField(blank=True, max_length=200, verbose_name='Miejsce zakupu')),
                ('receipt_photo', models.ImageField(blank=True, null=True, upload_to='equipment/receipts/%Y/%m/', verbose_name='Zdjęcie paragonu')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Sprzedany')),
                ('sold_date', models.DateField(blank=True, null=True, verbose_name='Data sprzedaży')),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cena sprzedaży')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to=settings.AUTH_USER_MODEL, verbose_name='Właściciel')),
            ],
            options={
                'verbose_name': 'Narzędzie/Sprzęt',
                'verbose_name_plural': 'Narzędzia/Sprzęt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Data przypisania')),
                ('end_date', models.DateField(blank=True, help_text='Puste jeśli sprzęt nadal jest przypisany', null=True, verbose_name='Data zwolnienia')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('assigned_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_assignments', to='renovation.property', verbose_name='Nieruchomość')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='renovation.equipment', verbose_name='Sprzęt')),
            ],
            options={
                'verbose_name': 'Przypisanie sprzętu',
                'verbose_name_plural': 'Przypisania sprzętu',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='equipment/photos/%Y/%m/', verbose_name='Zdjęcie')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Opis zdjęcia')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data przesłania')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='renovation.equipment', verbose_name='Sprzęt')),
            ],
            options={
                'verbose_name': 'Zdjęcie sprzętu',
                'verbose_name_plural': 'Zdjęcia sprzętu',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['owner', 'is_sold'], name='renovation__owner_i_8d8557_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['is_sold', '-created_at'], name='renovation__is_sold_494fea_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentassignment',
            index=models.Index(fields=['equipment', 'end_date'], name='renovation__equipme_c27a6a_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentassignment',
            index=models.Index(fields=['assigned_property', 'end_date'], name='renovation__assigne_4b2de8_idx'),
        ),
    ]
