# Generated by Django 5.2.9 on 2025-12-30 20:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renovation', '0006_equipment_equipmentassignment_equipmentphoto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='renovation.property', verbose_name='Nieruchomość'),
        ),
        migrations.AlterField(
            model_name='room',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='renovation.property', verbose_name='Nieruchomość'),
        ),
        migrations.CreateModel(
            name='RenovationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('status', models.CharField(choices=[('not_started', 'Nie rozpoczęto'), ('in_progress', 'W trakcie'), ('completed', 'Zakończono'), ('on_hold', 'Wstrzymano')], default='not_started', max_length=20, verbose_name='Status')),
                ('priority', models.IntegerField(default=3, help_text='1 = najwyższy, 5 = najniższy', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Priorytet')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Data rozpoczęcia')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Data zakończenia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('related_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renovation_tasks', to='renovation.property', verbose_name='Nieruchomość')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renovation_tasks', to='renovation.room', verbose_name='Pomieszczenie')),
            ],
            options={
                'verbose_name': 'Zadanie remontowe',
                'verbose_name_plural': 'Zadania remontowe',
                'ordering': ['status', 'priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nazwa przedmiotu')),
                ('description', models.TextField(blank=True, verbose_name='Szczegóły')),
                ('status', models.CharField(choices=[('not_started', 'Nie kupiono'), ('ordered', 'Zamówiono'), ('bought', 'Kupiono i dostarczone')], default='not_started', max_length=20, verbose_name='Status')),
                ('vendor', models.CharField(blank=True, max_length=100, verbose_name='Sklep')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Szacowana cena')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ilość')),
                ('unit', models.CharField(choices=[('piece', 'szt.'), ('kg', 'kg'), ('liter', 'l'), ('meter', 'm'), ('m2', 'm²'), ('package', 'opakowanie')], default='piece', max_length=20, verbose_name='Jednostka miary')),
                ('priority', models.IntegerField(default=3, help_text='1 = najwyższy, 5 = najniższy', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Priorytet')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('related_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_items', to='renovation.property', verbose_name='Nieruchomość')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_items', to='renovation.room', verbose_name='Pomieszczenie')),
            ],
            options={
                'verbose_name': 'Przedmiot do kupienia',
                'verbose_name_plural': 'Przedmioty do kupienia',
                'ordering': ['status', 'priority', '-created_at'],
            },
        ),
    ]
